python/django_ecom/UserMember/urls.py
from django.urls import path,include
from . import views

app_name = 'register'
urlpatterns = [
    path('register/',views.registerUser.as_view(), name='register'),
    path('login/',views.loginUser.as_view(),name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('loginOK/',views.loginOK.as_view(),name="loginOK"),
]

python/django_ecom/contact/urls.py
from django.urls import path,include
from . import views

app_name = 'contact'
urlpatterns = [
    path('',views.contact.as_view(), name='contact'),
    #path('getContact/',views.getContact,name="getContact")
]

python/django_ecom/django_ecom/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from ecom import views

urlpatterns = [
    path('admin/',admin.site.urls),
    path('',include('home.urls')),
    path('post/',include('post.urls')),
    path('contact/',include('contact.urls')),
    path('UserMember/',include('UserMember.urls')),
]

python/django_ecom/home/urls.py
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 26 16:06:23 2021

@author: duy
"""

from django.urls import path,include
from . import views

app_name = 'home'
urlpatterns = [
    path('',views.index, name='home'),
]

python/django_ecom/post/urls.py
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 26 16:24:42 2021

@author: duy
"""

from django.urls import path,include
from . import views

app_name = "post"
urlpatterns = [
    path('',views.index,name="blog"),
    path('<int:id>/',views.postDetail,name='postDetail'),
]

python/django_ecom/UserMember/models.py
from django.db import models

# Create your models here.

python/django_ecom/contact/models.py
from django.db import models

# Create your models here.
class contactForm(models.Model):
    username = models.CharField(max_length = 25)
    email = models.EmailField()
    body = models.TextField()
    
    def __str__(self):
    	return self.username

python/django_ecom/ecom/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
import django.utils.safestring as safestring

# Create your models here.
class Type(models.Model):
    name = models.CharField(max_length=200)
    active = models.BooleanField("Is Active", default=True)
    
    def __str__(self):
        return self.name


class Product(models.Model):
    type_id = models.ForeignKey(Type, on_delete=models.CASCADE)
    name = models.CharField("Product Name", max_length=200)
    price = models.IntegerField("Price", default=0)
    quantity = models.IntegerField("Quantity", default=0)
    image = models.ImageField(upload_to='uploads/%Y/%m/%d/')
    description = models.TextField("Description")
    
    def image_tag(self):
        if self.image:
            return safestring.mark_safe('<img src="%s%s" width="150" height="150" />' % (settings.MEDIA_URL, self.image))
        else:
            return ""

    image_tag.short_description = 'Image'
    image_tag.allow_tags = True
    
    def __str__(self):
        return self.name
    

python/django_ecom/home/models.py
from django.db import models

# Create your models here.

python/django_ecom/post/models.py
from django.db import models

# Create your models here.
class postForm(models.Model):
	title = models.CharField(max_length=25)
	body = models.TextField()
	create_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title

python/django_ecom/UserMember/forms.py
from django import forms

class registerForm(forms.Form):
	username = forms.CharField(max_length=25)
	email = forms.EmailField()
	password = forms.CharField(max_length=20,widget=forms.PasswordInput)

class loginForm(forms.Form):
	username = forms.CharField(max_length=25)
	password = forms.CharField(max_length=20,widget=forms.PasswordInput)

python/django_ecom/contact/forms.py
from django import forms
from .models import contactForm

class contact_Form(forms.ModelForm):
	class Meta:
		model = contactForm
		fields = ['username','email','body']

python/django_ecom/UserMember/views.py
from django.shortcuts import render
from .forms import registerForm,loginForm
from django.views import View
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class registerUser(View):
	def get(self,request):
		rF = registerForm
		return render(request,'UserMember/register.html',{'rF':rF})
	def post(self,request):
		username = request.POST['username']
		email = request.POST['email']
		password = request.POST['password']

		user = User.objects.create_user(username,email,password)
		user.save()
		return HttpResponse("OK!")

class loginUser(View):
	def get(self,request):
		lF = loginForm
		return render(request,'UserMember/login.html',{'lF':lF})
	def post(self,request):
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request,username=username,password=password)
		if user is not None:
			login(request,user)
			return render(request,'UserMember/loginOK.html')
		else:
			return HttpResponse("NO!")

def logoutUser(request):
	logout(request)
	return render(request,'home/index.html')

class loginOK(LoginRequiredMixin, View):
	login_url='/login/'
	def get(self,request):
		return render(request,'UserMember/loginOK.html')

python/django_ecom/contact/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import contact_Form
from django.views import View

class contact(View):
	def get(self,request):
		cc = {'cf123':contact_Form}
		return render(request,'contact/contact.html',cc)
	def post(self,request):
		if request.method == "POST":
			cf123 = contact_Form(request.POST)
			if cf123.is_valid():
				cf123.save()
				return render(request,'contact/contact.html',cc)
		else:
			return HttpResponse("no POST")

python/django_ecom/ecom/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import Http404
from django.shortcuts import render
from .models import Type, Product

# Create your views here.
def index(request):
    type_objs = Type.objects.filter(active__exact=True)
    context = {
        'type_objs': type_objs,
    }
    return render(request, "ecom/type.html", context)
    
def product(request, product_id):
    try:
        product = Product.objects.get(id=product_id)
    except Product.DoesNotExist:
        raise Http404("Product does not exist")
    return render(request, 'ecom/product.html', {'product': product})
    

python/django_ecom/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def index(request):
    return render(request,'home/index.html')

python/django_ecom/post/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import postForm
# Create your views here.
def index(request):
	pF = postForm.objects.all()
	return render(request,'post/post.html',{'pF':pF})
def postDetail(request,id):
	pD = postForm.objects.get(id = id)
	return render(request,'post/postDetail.html',{'pD':pD})

python/django_ecom/UserMember/templates/UserMember/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Login</title>
	<link rel="stylesheet" href="">
</head>
<body>
	<form action="" method="POST" accept-charset="utf-8">
		{% csrf_token %}
		{{lF.as_p}}
		<input type="submit" name="">
	</form>
</body>
</html>

python/django_ecom/UserMember/templates/UserMember/loginOK.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>OK LOGIN</title>
	<link rel="stylesheet" href="">
</head>
<body>
	<h1>OK</h1>
	<p><a href="{% url 'register:logout' %}">Logout</a></p>
</body>
</html>

python/django_ecom/UserMember/templates/UserMember/register.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Register New User</title>
	<link rel="stylesheet" href="">
</head>
<body>
	<form action="{% url 'register:register' %}" method="post" accept-charset="utf-8">
		{% csrf_token %}
		{{rF.as_p}}
		<input type="submit" name="">
	</form>
</body>
</html>

python/django_ecom/contact/templates/contact/contact.html
{% extends 'home/base.html' %}
    {% block content %}
    	<form action="{% url 'contact:contact' %}" method="post">
    		{% csrf_token %}
    		{{cf123.as_p}}
    		<input type="submit" name="">
    	</form>
    {% endblock %}

python/django_ecom/ecom/templates/ecom/product.html
<!DOCTYPE html>
<html lang="vi">
    <head>
        <meta charset="UTF-8">
        <title>Ecom</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cosmo/bootstrap.min.css" rel="stylesheet" integrity="sha384-h21C2fcDk/eFsW9sC9h0dhokq5pDinLNklTKoxIZRUn3+hvmgQSffLLQ4G4l2eEr" crossorigin="anonymous">
    </head>
    
    <script defer src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <body>
        <nav class="navbar navbar-default navbar-expand-sm" style="background-color: #212121;">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="/">Django Ecom</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-items">
            <ul class="nav navbar-nav">   
            </ul>    
            <ul class="nav navbar-nav navbar-right">
                <li><span class="navbar-brand slogan">Welcome to Django</span></li>
                <li>
                      <form class="navbar-form navbar-left" role="search">
                        <div class="form-group">
                          <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                      </form>
                </li>
            </ul>
            </div>
          </div>
        </nav>
        
        <div class="container">
        <div class="col-sm-8">
            <div class="row">
                <div class="col-xs-6">
                    <a href="{% url 'product' product.id %}"><img src="/media/{{ product.image }}" /></a>
                </div>
                <div class="col-xs-3">
                    <b>Product Name</b><br/>
                    <b>Price</b><br/>
                    <b>Quantity</b><br/>
                    <b>Description</b><br/>
                </div>
                <div class="col-xs-3">
                    {{product.name}}<br/>
                    ${{product.price}}<br/>
                    {{product.quantity}}<br/>
                    {{product.description}}<br/>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
        </div>
        </div>
    </<body>
</html>

python/django_ecom/ecom/templates/ecom/type.html
<!DOCTYPE html>
<html lang="vi">
    <head>
        <meta charset="UTF-8">
        <title>Ecom</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cosmo/bootstrap.min.css" rel="stylesheet" integrity="sha384-h21C2fcDk/eFsW9sC9h0dhokq5pDinLNklTKoxIZRUn3+hvmgQSffLLQ4G4l2eEr" crossorigin="anonymous">
    </head>
    
    <script defer src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <body>
        
        <nav class="navbar navbar-default navbar-expand-sm" style="background-color: #212121;">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="/">Django Ecom</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-items">
            <ul class="nav navbar-nav">   
            </ul>    
            <ul class="nav navbar-nav navbar-right">
                <li><span class="navbar-brand slogan">Welcome to Django</span></li>
                <li>
                      <form class="navbar-form navbar-left" role="search">
                        <div class="form-group">
                          <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                      </form>
                </li>
            </ul>
            </div>
          </div>
        </nav>
        
        <div class="container">
        <div id="categories-tab">
            <ul class="nav nav-tabs">
            {% for type in type_objs %}
                {% if forloop.first %}
                    <li class="h4 active">
                        <a id="tab-{{ type.name | slugify }}" href="#{{ type.name | slugify }}" data-toggle="tab" aria-expanded="true">
                            <i class="fa fa-folder-o" aria-hidden="true"></i> &nbsp;
                            {{ type.name }}
                        </a>
                    </li>
                {% else %}
                    <li class="h4">
                        <a id="tab-{{ type.name | slugify }}" href="#{{ type.name | slugify }}" data-toggle="tab" aria-expanded="false">
                            <i class="fa fa-folder-o" aria-hidden="true"></i> &nbsp;
                            {{ type.name }}
                        </a>
                    </li>
                {% endif %}        
            {% endfor %}                
            </ul>
            <div id="product-in-category" class="tab-content">
            {% for type in type_objs %}
                {% if forloop.first %}
                    <div class="tab-pane fade active in" id="{{ type.name | slugify }}">
                {% else %}
                    <div class="tab-pane fade" id="{{ type.name | slugify }}">
                {% endif %}
                        <p>
                        <div class="row post-grid">
                            {% for product in type.product_set.all %}
                                {% if product.quantity > 0 %}
                                <div class="col-sm-4">
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <a href="{% url 'product' product.id %}"><img src="/media/{{ product.image }}" /></a>
                                        </div>
                                    </div>
                                    <p>
                                        <p>
                                        <span><i class="fa fa-dollar" aria-hidden="true"></i>&nbsp; {{product.price}}</span>
                                        &nbsp; &nbsp; 
                                        <span><i class="fa fa-cart-plus" aria-hidden="true"></i>&nbsp; {{product.quantity}}</span>
                                        <a href="{% url 'product' product.id %}"><h4>{{ product.name }}</h4>        </a>    
                                    </p>
                                </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>        
            {% endfor %}
            </div>
        </div>
        </div>
    </<body>
</html>

python/django_ecom/home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="menu">
        <ul>
            <li><a href="{% url 'home:home'%}">Home</a></li>
            <li><a href="{% url 'post:blog'%}">List</a></li>
            <li><a href="{% url 'contact:contact'%}">Contact</a></li>
            <li><a href="{% url 'register:register'%}">Register</a></li>
            <li><a href="{% url 'register:login'%}">Login</a></li>
        </ul>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

python/django_ecom/home/templates/home/index.html
{% extends 'home/base.html' %}
    {% block content %}
        <h1>this is a heading 1 of a home
    {% endblock %}

python/django_ecom/post/templates/post/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">-->
    <title>Document</title>
</head>
<body>
    <div class="menu">
        <ul>
            <li><a href="{% url 'home:home'%}">Home</a></li>
            <li><a href="{% url 'post:blog'%}">List</a></li>
            <li><a href="{% url 'contact:contact'%}">Contact</a></li>
            <li><a href="{% url 'register:register'%}">Register</a></li>
            <li><a href="{% url 'register:login'%}">Login</a></li>
        </ul>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

python/django_ecom/post/templates/post/post.html
{% extends 'post/base.html' %}
    {% block content %}
        {% for item in pF %}
        	<p><a href="{% url 'post:postDetail' item.id %}">{{item.title}}</a></p>
        {% endfor %}
    {% endblock %}

python/django_ecom/post/templates/post/postDetail.html
{% extends 'post/base.html' %}
    {% block content %}
    	{{pD.body}}
    	<p style="font-size:10px">{{pD.create_at}}</p>
    {% endblock %}